#ifndef _IRIDIUM_CONFIG_H_INCLUDED_
#define _IRIDIUM_CONFIG_H_INCLUDED_

// Типы протоколов
//#define IRIDIUM_ENABLE_TCP_PROTOCOL
//#define IRIDIUM_ENABLE_UDP_PROTOCOL
#define IRIDIUM_ENABLE_BUS_PROTOCOL

// Включение доступности методов централизованной сети в зависимости от выбранного протокола
#if defined(IRIDIUM_ENABLE_TCP_PROTOCOL)
#define IRIDIUM_ENABLE_LONG_ADDRESS
#endif

// Шифрование
//#define IRIDIUM_ENABLE_SIMPLE_CIPHER               // Включение простейшего шифрования
//#define IRIDIUM_ENABLE_GRASSHOPPER_CIPHER          // Включение блочного шифрования "кузнечик"
//#define IRIDIUM_ENABLE_AES256_CIPHER               // Включение блочного шифрования AES256

//#define IRIDIUM_ENABLE_IV                          // Включение вектора инициализации

// Включение шифрования
#if defined(IRIDIUM_ENABLE_SIMPLE_CIPHER) || defined(IRIDIUM_ENABLE_GRASSHOPPER_CIPHER) || defined(IRIDIUM_ENABLE_AES256_CIPHER)
#define IRIDIUM_ENABLE_CIPHER

// Если включен какой либо блочный шифр, включаем поддержку алгоритма Диффи-Хэллмана
#if defined(IRIDIUM_ENABLE_GRASSHOPPER_CIPHER) || defined(IRIDIUM_ENABLE_AES256_CIPHER)
#define IRIDIUM_ENABLE_DH
#endif   // defined(IRIDIUM_ENABLE_GRASSHOPPER_CIPHER) || defined(IRIDIUM_ENABLE_AES256_CIPHER)
#endif   // defined(IRIDIUM_ENABLE_SIMPLE_CIPHER) || defined(IRIDIUM_ENABLE_GRASSHOPPER_CIPHER) || defined(IRIDIUM_ENABLE_AES256_CIPHER)

// Настройка CRC8 и CRC16
//#define IRIDIUM_ENABLE_FAST_CRC8
//#define IRIDIUM_ENABLE_FAST_CRC16

// Конфигурация протокола
// Системные
//#define IRIDIUM_CONFIG_SYSTEM_PING_MASTER
#define IRIDIUM_CONFIG_SYSTEM_PING_SLAVE
//#define IRIDIUM_CONFIG_SYSTEM_SEARCH_MASTER
#define IRIDIUM_CONFIG_SYSTEM_SEARCH_SLAVE
//#define IRIDIUM_CONFIG_SYSTEM_DEVICE_INFO_MASTER
#define IRIDIUM_CONFIG_SYSTEM_DEVICE_INFO_SLAVE
//#define IRIDIUM_CONFIG_SYSTEM_SET_LID_MASTER
#define IRIDIUM_CONFIG_SYSTEM_SET_LID_SLAVE
//#define IRIDIUM_CONFIG_SYSTEM_SMART_API_MASTER
#define IRIDIUM_CONFIG_SYSTEM_SMART_API_SLAVE
#define IRIDIUM_CONFIG_SYSTEM_BLINK_SLAVE

// Работа с глобальными переменными
#define IRIDIUM_CONFIG_SET_VARIABLE_MASTER
#define IRIDIUM_CONFIG_SET_VARIABLE_SLAVE
#define IRIDIUM_CONFIG_GET_VARIABLE_MASTER
#define IRIDIUM_CONFIG_GET_VARIABLE_SLAVE
// Работа с каналами обратной связи
//#define IRIDIUM_CONFIG_GET_TAGS_MASTER
#define IRIDIUM_CONFIG_GET_TAGS_SLAVE
//#define IRIDIUM_CONFIG_LINK_TAG_AND_VARIABLE_MASTER
#define IRIDIUM_CONFIG_LINK_TAG_AND_VARIABLE_SLAVE
//#define IRIDIUM_CONFIG_GET_TAG_DESCRIPTION_MASTER
#define IRIDIUM_CONFIG_GET_TAG_DESCRIPTION_SLAVE
//#define IRIDIUM_CONFIG_SET_TAG_VALUE_MASTER
#define IRIDIUM_CONFIG_SET_TAG_VALUE_SLAVE
//#define IRIDIUM_CONFIG_GET_TAG_VALUE_MASTER
#define IRIDIUM_CONFIG_GET_TAG_VALUE_SLAVE
// Работа с каналами управления
//#define IRIDIUM_CONFIG_GET_CHANNELS_MASTER
#define IRIDIUM_CONFIG_GET_CHANNELS_SLAVE
//#define IRIDIUM_CONFIG_SET_CHANNEL_VALUE_MASTER
#define IRIDIUM_CONFIG_SET_CHANNEL_VALUE_SLAVE
//#define IRIDIUM_CONFIG_LINK_CHANNEL_AND_VARIABLE_MASTER
#define IRIDIUM_CONFIG_LINK_CHANNEL_AND_VARIABLE_SLAVE
//#define IRIDIUM_CONFIG_GET_CHANNEL_DESCRIPTION_MASTER
#define IRIDIUM_CONFIG_GET_CHANNEL_DESCRIPTION_SLAVE
//#define IRIDIUM_CONFIG_GET_CHANNEL_VALUE_MASTER
#define IRIDIUM_CONFIG_GET_CHANNEL_VALUE_SLAVE
// Работа с потоками
//#define IRIDIUM_CONFIG_STREAM_OPEN_MASTER
#define IRIDIUM_CONFIG_STREAM_OPEN_SLAVE
//#define IRIDIUM_CONFIG_STREAM_BLOCK_MASTER
//#define IRIDIUM_CONFIG_STREAM_BLOCK_SLAVE
//#define IRIDIUM_CONFIG_STREAM_CLOSE_MASTER
//#define IRIDIUM_CONFIG_STREAM_CLOSE_SLAVE

#endif // _IRIDIUM_CONFIG_H_INCLUDED_
